version: '3'
services:
  spring-app:
    image: gowthamr733/kaibur 
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://gowthamr733:goutham@cluster0.p1yc3mi.mongodb.net/kaibur?retryWrites=true&w=majority"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
