apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaibur-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: kaibur
  template:
    metadata:
      labels:
        app: kaibur
    spec:
      containers:
        - name: kaibur
          image: gowthamr733/kaibur
          ports:
            - containerPort: 8080